### ISSUE TITLE
Addon not updating sensor values when frequency is lower than 5 min.

### ISSUE THREAD

**Issue by pameruoso** [muppet3000/homeassistant-grott#103]
Hi, I changed the frequency in my data logger to 1 min.

In grott and by manually subscribing to the energy/growatt topic in homeasssistant mqtt addon I correctly see the values coming in every 1 minute.

On the other side the addon is only updating the values every 5 minutes... Is there a special parameter that has to be changed to fetch the values every 1 minute?

**Comment by muppet3000** [comment]
If the values are appearing in MQTT then that's when they're updated in the integration, the integration should receive the update immediately from MQTT when the value is updated and it should be available in the UI.
Are the values actually changing? The integration will only show an updated time for the value if it has actually changed.

**Comment by pameruoso** [comment]
![image](https://github.com/user-attachments/assets/b6565ad3-9c2d-42cf-96f3-9ecb6c176446)

![image](https://github.com/user-attachments/assets/cd50a5c6-83e7-4018-97a1-e2af1fe43497)
Just an example related to the battery. Am i wrong?

**Comment by muppet3000** [comment]
In the right hand side of that second picture, what is the source of that information? Is that output from the Grott service or from the MQTT receiver?

**Comment by pameruoso** [comment]
that is the output of mqtt addon in homeassistant in listening mode for energy/growatt topic, and there i receive one message every 1 minute

**Comment by muppet3000** [comment]
I've double checked the code and we have an asynchronous subscription to the mqtt topic, meaning that as soon as the MQTT service tells us about the message, we process it:
https://github.com/muppet3000/homeassistant-grott/blob/main/custom_components/grott/sensor.py#L98-L100

Therefore, I cannot explain the situation you're seeing.

Are you able to put the integration into debug logging mode and look at when you get the "Received message:" logs, and then see if they appear at the same time as the MQTT message from the right hand side?

I've never seen behaviour like this before and it doesn't really make sense. 

How do you have grott etc. installed? are they all as standalone services or are you using the egguy addon?

**Comment by pameruoso** [comment]
so Mqtt is a lxc container running mosquitto, grott is another lxc container and homeassistant is the full vm version. I have been changing around parameters to the grott config and now I have set sendbuff to false and fixed my timezone to the server instead of auto inside grott. I ve been observing the mqtt messages and sometime it was sending a timestamp 1 hour back (the grott server had utc while the datalogger has CET). I think that with auto sometimes grott was sending a different timezone in the mqtt message hence breaking ( i think) the possibility for HA or the addon to understand what that message refers to.

after this changes it seems like now the messages are immediately processed as soon as they hit mosquitto.

**Comment by muppet3000** [comment]
Amazing!
The various timezone things always messes things up. I'm glad you were able to solve it. 
I'll leave this ticket open in case the problem comes back, but once you're happy please can you close it?

**Comment by pameruoso** [comment]
Will definitely close it after observing it. Thanks!

**Comment by pameruoso** [comment]
Closing. It is working as expected
