### ISSUE TITLE
Crashed - Connection reset by peer

### ISSUE THREAD

**Issue by mriksman** [muppet3000/homeassistant-grott#12]
This had been running great for a few days. 

Then I find I was no longer receiving data updates. 

Portainer shows it existed 3 days ago.
![image](https://github.com/muppet3000/homeassistant-grott/assets/20112339/cce25c68-ea7b-454b-b552-e90f874d1028)

I check the logs;
```
	 - Growatt packet received:
		  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.18.0.7', 34384), raddr=('47.91.67.66', 5279)>
	 - Data less then minimum record length, data not processed
	 - Growatt packet received:
		  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.18.0.7', 34384)>
Traceback (most recent call last):
  File "/app/grott.py", line 35, in <module>
    proxy.main(conf)
  File "/app/grottproxy.py", line 144, in main
    self.on_recv(conf)
  File "/app/grottproxy.py", line 235, in on_recv
    self.channel[self.s].send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by mriksman** [comment]
I've added this to my `docker-compose`
```
 restart: unless-stopped
```
So it should recover automatically now. Not sure if you want to investigate this, close it, or change your Docker Compose template to include this.

**Comment by bartpaeleman** [comment]
@mriksman I think this should be reported to https://github.com/johanmeijer/grott

**Comment by muppet3000** [comment]
> I've added this to my `docker-compose`
> 
> ```
>  restart: unless-stopped
> ```
> 
> So it should recover automatically now. Not sure if you want to investigate this, close it, or change your Docker Compose template to include this.

I've been on holiday and I'm just now catching up. Happy to include this in the docker-compose.
While the bug that caused it to happen should be reported to the grott repo, there's no harm in catering for it here.
