### ISSUE TITLE
SPF inverter sensors

### ISSUE THREAD

**Issue by msrheidema** [muppet3000/homeassistant-grott#25]
Hi @muppet3000,

First thanks for all that you've done, this works pretty well.
However, the inverter that I use is an growatt-spf-6000t and a lot of the values that grott sends out for it are not in the current sensors_mqtt.py.

```{
   "device":"X",
   "time":"2023-07-17T10:10:13",
   "buffered":"no",
   "values":{
      "datalogserial":"X",
      "pvserial":"X",
      "pvstatus":0,
      "vpv1":1335,
      "vpv2":1335,
      "ppv1":2940,
      "ppv2":2940,
      "buck1curr":108,
      "buck2curr":0,
      "op_watt":0,
      "pvpowerout":0,
      "op_va":0,
      "acchr_watt":0,
      "acchr_VA":0,
      "bat_Volt":5320,
      "batterySoc":50,
      "bus_volt":0,
      "grid_volt":0,
      "line_freq":0,
      "outputvolt":9,
      "pvgridvoltage":9,
      "outputfreq":0,
      "invtemp":389,
      "dcdctemp":413,
      "loadpercent":0,
      "buck1_ntc":0,
      "buck2_ntc":0,
      "OP_Curr":0,
      "Inv_Curr":3,
      "AC_InWatt":0,
      "AC_InVA":0,
      "faultBit":0,
      "warningBit":0,
      "faultValue":0,
      "warningValue":0,
      "constantPowerOK":0,
      "epvtoday":13,
      "pvenergytoday":13,
      "epvtotal":1802,
      "eacCharToday":0,
      "eacCharTotal":1082,
      "ebatDischarToday":0,
      "ebatDischarTotal":1254,
      "eacDischarToday":0,
      "eacDischarTotal":0,
      "ACCharCurr":0,
      "ACDischarWatt":0,
      "ACDischarVA":0,
      "BatDischarWatt":0,
      "BatDischarVA":0,
      "BatWatt":-5880
   }
}
```

I have hereby attached an excel with the readable names where I could find them with the correct dividers.

[grott_spf_inverter.xlsx](https://github.com/muppet3000/homeassistant-grott/files/12071044/grott_spf_inverter.xlsx)

When you have a minute could you add them to the sensors_mqtt.py?

Thanks in advance

source for the names:
https://raw.githubusercontent.com/johanmeijer/grott/60b802ecdac130c07730cff7da3bcd50ef4be61c/grottconf.py
https://github.com/johanmeijer/grott/blob/60b802ecdac130c07730cff7da3bcd50ef4be61c/examples/Home%20Assistent/grott_ha.py

**Comment by muppet3000** [comment]
Thanks @msrheidema I'll see what I can do.
Not sure when I'll have a chance to implement them but it shouldn't be too hard.

**Comment by wbrocker** [comment]
@muppet3000 First of all, thanks for your effort in getting all of this setup!

I have been following this project for a very long time, and managed to eventually implement it today on my ES SPF 5000 inverters. Setup was fairly straight forward (easier than what I expected), but I am also missing some of the values as mentioned in this thread. I have set grott inv to 'default', (I tried SPF as well, but got even less info) and I am not getting any battery information which is critical for some of my automations.

For now, I am running GROTT as well as the initial Growatt integration which locks me out every morning... When I have some more time I will also play around a bit more to ensure I am not missing anything.

**Comment by msrheidema** [comment]
@wbrocker Can you post one of your mqtt messages here so that we can see if it's the same as mine?

Anyways, if it's the same and the only thing you care about is the battery percentage what I did was in:

https://github.com/muppet3000/homeassistant-grott/blob/main/custom_components/grott/sensors/sensors_mqtt.py
(so in your homeassistant's `/custom_components/grott/sensors/` directory which is in located in config)

Change line 884 the following:
`    "func": lambda js: js['values']["bms_soc"],`
into
`    "func": lambda js: js['values']["batterySoc"],`

**Comment by wbrocker** [comment]
@msrheidema Currently getting this:

{"device": "RKG5B150BH", "time": "2023-08-11T17:37:10", "buffered": "no", "values": {"datalogserial": "DDD0B02027", "pvserial": "RKG5B150BH", "pvstatus": 12, "pvpowerin": 97124352, "pv1voltage": 0, "pv1current": 60, "pv1watt": 0, "pv2voltage": 1, "pv2current": 0, "pv2watt": 3000, "pvpowerout": 3340, "pvfrequentie": 0, "pvgridvoltage": 0, "pvgridcurrent": 0, "pvgridpower": 4900, "pvgridvoltage2": 70, "pvgridcurrent2": 3908, "pvgridpower2": 146084743, "pvgridvoltage3": 2306, "pvgridcurrent3": 5002, "pvgridpower3": 65781, "pvenergytoday": 14483516, "pvenergytotal": 0, "totworktime": 0, "pvtemperature": 212, "pvipmtemperature": 0, "epv1today": 66, "epv1total": 59947, "epv2today": 0, "epv2total": 0, "epvtotal": 18}}

This is on the invtype=default setting. I am not even getting a bms_sock or batterySoc value...\

I actually do care about additional details as well... Thanks for the suggestion. I will have a look at that when I have a little bit more time.

**Comment by msrheidema** [comment]
Can you change your grott.ini to include

```grott.ini
[Generic]
invtype = spf
```

And see if you get more data? Cause this doesn't have the raw data for the battery.

**Comment by wbrocker** [comment]
Sorry, was away from my pc...
Made the change and I am getting this now:

{"device": "RKG5B150BH", "time": "2023-08-12T09:47:26", "buffered": "no", "values": {"datalogserial": "DDD0B02027", "pvserial": "RKG5B150BH", "pvstatus": 12, "vpv1": 1882, "vpv2": 0, "ppv1": 12570, "ppv2": 0, "buck1curr": 246, "buck2curr": 0, "op_watt": 2700, "pvpowerout": 2700, "op_va": 3220, "acchr_watt": 0, "acchr_VA": 0, "bat_Volt": 5090, "batterySoc": 79, "bus_volt": 4140, "grid_volt": 2299, "line_freq": 4998, "outputvolt": 2304, "pvgridvoltage": 2304, "outputfreq": 4998, "invtemp": 207, "dcdctemp": 189, "loadpercent": 54, "buck1_ntc": 245, "buck2_ntc": 0, "OP_Curr": 14, "Inv_Curr": 19, "AC_InWatt": 0, "AC_InVA": 0, "faultBit": 0, "warningBit": 0, "faultValue": 0, "warningValue": 0, "constantPowerOK": 1, "epvToday": 18, "pvenergytoday": 18, "epvTotal": 59965, "pvenergytotal": 59965, "eacCharToday": 20, "eacCharTotal": 5765, "ebatDischarToday": 9, "ebatDischarTotal": 18727, "eacDischarToday": 10, "eacDischarTotal": 17859, "ACCharCurr": 0, "ACDischarWatt": 2760, "ACDischarVA": 3340, "BatDischarWatt": 0, "BatDischarVA": 0, "BatWatt": -9460}}

Think I need to go through everything when I have some more time and try to map them. Looks like the info I need is in here.

**Comment by muppet3000** [comment]
If you're able to give me the names of the ones that are missing and what their "human readable" name is, I should be able to map them through without too much effort.
I just haven't had much spare time recently, might get some.time in the evenings next week though.

**Comment by msrheidema** [comment]
@muppet3000 most of the ones he needs are also with the human readable name in the excel that I posted in the first comment.

I could do a pull request so you don’t have to do it.

I just have one question: for the mqtt field is there a logic? Or do I just continue the numbering up?

@wbrocker the results you posted are with sph or spf so that I put the right comment next to the added values.

**Comment by muppet3000** [comment]
> @muppet3000 most of the ones he needs are also with the human readable name in the excel that I posted in the first comment.
> 
> I could do a pull request so you don’t have to do it.
> 
> I just have one question: for the mqtt field is there a logic? Or do I just continue the numbering up?
> 
> @wbrocker the results you posted are with sph or spf so that I put the right comment next to the added values.

Sorry, yes I completely forgot there was a spreadsheet with it all in.

The numbering is just a case of increasing them yes. Where I've put things in 'out of order' I've left comments at the bottom of the file.
I'd be very welcoming of a PR, I'll happily do a review and we can collaborate on it.

**Comment by wbrocker** [comment]
@msrheidema  sorry for my slow response... Not at my pc a lot today...
It's currently set on 'spf'.
I will probably only get to look at it in more detail tomorrow if I get a chance, but willing to help where I can.

**Comment by Nicolas76x** [comment]
Hi

Would love to be of assistance, 6 spf5000 in a 2s3p config, so lot's of data to be picked up and organised.
Can help with the programming part if you like but new at MQQT and home assistant so please be gentle.

Thanks

**Comment by Nicolas76x** [comment]
And @muppet3000 great work!

**Comment by msrheidema** [comment]
I did not figure out yet what these ones do:

```
#x      "op_va":0,
#x      "loadpercent":0,
#x      "buck1_ntc":0,
#x      "buck2_ntc":0,
#x      "AC_InVA":0,
#x      "faultBit":0,
#x      "warningBit":0,
#x      "faultValue":0,
#x      "warningValue":0,
#x      "constantPowerOK":0,
#x      "ACCharCurr":0,
#x      "ACDischarWatt":0,
#x      "ACDischarVA":0,
#x      "BatDischarWatt":0,
#x      "BatDischarVA":0,
#x      "BatWatt":-5880
```

We should be able to extract them from
https://raw.githubusercontent.com/egguy/grott/feature/ha-extension/examples/Home%20Assistent/grott_ha.py

However I did add some extra ones, to get them working  add this to your `/custom_components/grott/sensors/sensors_mqtt.py` until @muppet3000 has time to include them.
I'm not sure I did the mdi's correctly so feel free to let me know if I mislabeled some of the data.
https://github.com/muppet3000/homeassistant-grott/blob/main/custom_components/grott/sensors/sensors_mqtt.py
which is located in your homeassistants config dir

```
#additions for SPF inverters
#The following are missing and need to be researched
#the icon's also need to be checked
#x      "op_va":0,
#x      "loadpercent":0,
#x      "buck1_ntc":0,
#x      "buck2_ntc":0,
#x      "AC_InVA":0,
#x      "faultBit":0,
#x      "warningBit":0,
#x      "faultValue":0,
#x      "warningValue":0,
#x      "constantPowerOK":0,
#x      "ACCharCurr":0,
#x      "ACDischarWatt":0,
#x      "ACDischarVA":0,
#x      "BatDischarWatt":0,
#x      "BatDischarVA":0,
#x      "BatWatt":-5880

  {
    "name": "PV1 Voltage",
    "device_class": SensorDeviceClass.VOLTAGE,
    "unit_of_measurement": UnitOfElectricPotential.VOLT,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:solar-power",
    "func": lambda js: js['values']["vpv1"],
    "divider": 10,
    "unique_name": "mqtt_104",
  },
    {
    "name": "PV2 Voltage",
    "device_class": SensorDeviceClass.VOLTAGE,
    "unit_of_measurement": UnitOfElectricPotential.VOLT,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:solar-power",
    "func": lambda js: js['values']["vpv2"],
    "divider": 10,
    "unique_name": "mqtt_105",
  },
  {
    "name": "PV1 Current",
    "device_class": SensorDeviceClass.CURRENT,
    "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:solar-power",
    "func": lambda js: js['values']["buck1curr"],
    "divider": 10,
    "unique_name": "mqtt_106",
  },
  {
    "name": "PV2 Current",
    "device_class": SensorDeviceClass.CURRENT,
    "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:solar-power",
    "func": lambda js: js['values']["buck2curr"],
    "divider": 10,
    "unique_name": "mqtt_107",
  },
  {
    "name": "PV1 Power",
    "device_class": SensorDeviceClass.POWER,
    "unit_of_measurement": UnitOfPower.WATT,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:solar-power",
    "func": lambda js: js['values']["ppv1"],
    "divider": 10,
    "unique_name": "mqtt_108",
  },
  {
    "name": "PV2 Power",
    "device_class": SensorDeviceClass.POWER,
    "unit_of_measurement": UnitOfPower.WATT,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:solar-power",
    "func": lambda js: js['values']["ppv2"],
    "divider": 10,
    "unique_name": "mqtt_109",
  },
  {
    "name": "Inverter Consumption Power",
    "device_class": SensorDeviceClass.POWER,
    "unit_of_measurement": UnitOfPower.WATT,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:home-lightning-bolt",
    "func": lambda js: js['values']["op_watt"],
    "divider": 10,
    "unique_name": "mqtt_110",
  },
#   {
#     "name": "Output apparent power",
#     "device_class": SensorDeviceClass.POWER,
#     "unit_of_measurement": UnitOfPower.WATT, #Not sure if this is the correct one for this
#     "state_class": SensorStateClass.MEASUREMENT,
#     "icon": "mdi:home-lightning-bolt",
#     "func": lambda js: js['values']["op_va"],
#     "divider": 10,
#     "unique_name": "mqtt_111",
#   },
  {
    "name": "Storage charging grid",
    "device_class": SensorDeviceClass.POWER,
    "unit_of_measurement": UnitOfPower.WATT,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:home-lightning-bolt",
    "func": lambda js: js['values']["acchr_watt"],
    "divider": 10,
    "unique_name": "mqtt_112",
  },
#   {
#     "name": "Storage charging grid reactive power",
#     "device_class": SensorDeviceClass.POWER,
#     "unit_of_measurement": UnitOfPower.WATT, #Not sure if this is the correct one for this
#     "state_class": SensorStateClass.MEASUREMENT,
#     "icon": "mdi:home-lightning-bolt",
#     "func": lambda js: js['values']["acchr_VA"],
#     "divider": 10,
#     "unique_name": "mqtt_113",
#   },
  {
    "name": "Battery Voltage",
    "device_class": SensorDeviceClass.VOLTAGE,
    "unit_of_measurement": UnitOfElectricPotential.VOLT,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:home-battery",
    "func": lambda js: js['values']["bat_Volt"],
    "divider": 100,
    "unique_name": "mqtt_114",
  },
  {
    "name": "Battery state of charge",
    "device_class": SensorDeviceClass.BATTERY,
    "unit_of_measurement": PERCENTAGE,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:home-battery",
    "func": lambda js: js['values']["batterySoc"],
    "divider": 1,
    "unique_name": "mqtt_115",
  },
 {
    "name": "Inverter bus voltage",
    "device_class": SensorDeviceClass.VOLTAGE,
    "unit_of_measurement": UnitOfElectricPotential.VOLT,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:solar-power",
    "func": lambda js: js['values']["bus_volt"],
    "divider": 10,
    "unique_name": "mqtt_116",
  },
 {
    "name": "Grid voltage",
    "device_class": SensorDeviceClass.VOLTAGE,
    "unit_of_measurement": UnitOfElectricPotential.VOLT,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:solar-power",
    "func": lambda js: js['values']["grid_volt"],
    "divider": 10,
    "unique_name": "mqtt_117",
  },
  {
    "name": "Grid Frequency",
    "device_class": SensorDeviceClass.FREQUENCY,
    "unit_of_measurement": UnitOfFrequency.HERTZ,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:sine-wave",
    "func": lambda js: js['values']["line_freq"],
    "divider": 100,
    "unique_name": "mqtt_118",
  },
  {
    "name": "Output Voltage",
    "device_class": SensorDeviceClass.VOLTAGE,
    "unit_of_measurement": UnitOfElectricPotential.VOLT,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:flash",
    "func": lambda js: js['values']["outputvolt"],
    "divider": 10,
    "unique_name": "mqtt_119",
  },
  {
    "name": "Inverter output Frequency",
    "device_class": SensorDeviceClass.FREQUENCY,
    "unit_of_measurement": UnitOfFrequency.HERTZ,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:sine-wave",
    "func": lambda js: js['values']["outputfreq"],
    "divider": 100,
    "unique_name": "mqtt_120",
  },
  {
    "name": "Inverter Temperature",
    "device_class": SensorDeviceClass.TEMPERATURE,
    "unit_of_measurement": UnitOfTemperature.CELSIUS,
    "state_class": SensorStateClass.MEASUREMENT,
    "entity_category": EntityCategory.DIAGNOSTIC,
    "icon": "mdi:thermometer",
    "func": lambda js: js['values']["invtemp"],
    "divider": 10,
    "unique_name": "mqtt_121",
  },
  {
    "name": "Battery charger temperature",
    "device_class": SensorDeviceClass.TEMPERATURE,
    "unit_of_measurement": UnitOfTemperature.CELSIUS,
    "state_class": SensorStateClass.MEASUREMENT,
    "entity_category": EntityCategory.DIAGNOSTIC,
    "icon": "mdi:thermometer",
    "func": lambda js: js['values']["dcdctemp"],
    "divider": 10,
    "unique_name": "mqtt_122",
  },
  {
    "name": "Inverter consumption current",
    "device_class": SensorDeviceClass.CURRENT,
    "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:flash",
    "func": lambda js: js['values']["OP_Curr"],
    "divider": 10,
    "unique_name": "mqtt_123",
  },
  {
    "name": "Inverter current",
    "device_class": SensorDeviceClass.CURRENT,
    "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:flash",
    "func": lambda js: js['values']["Inv_Curr"],
    "divider": 10,
    "unique_name": "mqtt_124",
  },
  {
    "name": "Import from Grid Power",
    "device_class": SensorDeviceClass.POWER,
    "unit_of_measurement": UnitOfPower.WATT,
    "state_class": SensorStateClass.MEASUREMENT,
    "icon": "mdi:home-import-outline",
    "func": lambda js: js['values']["AC_InWatt"],
    "divider": 10,
    "unique_name": "mqtt_125",
  },
  {
    "name": "PV Energy - Today",
    "device_class": SensorDeviceClass.ENERGY,
    "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
    "state_class": SensorStateClass.TOTAL_INCREASING,
    "icon": "mdi:solar-power",
    "func": lambda js: js['values']["epvtoday"],
    "divider": 10,
    "unique_name": "mqtt_126",
  },
  {
    "name": "Battery Charged from AC - Today",
    "device_class": SensorDeviceClass.ENERGY,
    "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
    "state_class": SensorStateClass.TOTAL_INCREASING,
    "icon": "mdi:battery-arrow-up",
    "func": lambda js: js['values']["eacCharToday"],
    "divider": 10,
    "unique_name": "mqtt_127",
  },
    {
    "name": "Battery Charged from AC - Total",
    "device_class": SensorDeviceClass.ENERGY,
    "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
    "state_class": SensorStateClass.TOTAL,
    "icon": "mdi:battery-arrow-up",
    "func": lambda js: js['values']["eacCharTotal"],
    "divider": 10,
    "unique_name": "mqtt_128",
  },
    {
    "name": "Battery Discharged Energy - Today",
    "device_class": SensorDeviceClass.ENERGY,
    "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
    "state_class": SensorStateClass.TOTAL_INCREASING,
    "icon": "mdi:battery-arrow-down",
    "func": lambda js: js['values']["ebatDischarToday"],
    "divider": 10,
    "unique_name": "mqtt_129",
  },
  {
    "name": "Battery Discharged Energy - Total",
    "device_class": SensorDeviceClass.ENERGY,
    "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
    "state_class": SensorStateClass.TOTAL,
    "icon": "mdi:battery-arrow-down",
    "func": lambda js: js['values']["ebatDischarTotal"],
    "divider": 10,
    "unique_name": "mqtt_130",
  },
    {
    "name": "Grid consumption - Today",
    "device_class": SensorDeviceClass.ENERGY,
    "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
    "state_class": SensorStateClass.TOTAL_INCREASING,
    "icon": "mdi:battery-arrow-up",
    "func": lambda js: js['values']["eacDischarToday"],
    "divider": 10,
    "unique_name": "mqtt_131",
  },
  {
    "name": "Grid consumption - Total",
    "device_class": SensorDeviceClass.ENERGY,
    "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
    "state_class": SensorStateClass.TOTAL,
    "icon": "mdi:battery-arrow-up",
    "func": lambda js: js['values']["eacDischarTotal"],
    "divider": 10,
    "unique_name": "mqtt_132",
  },
```
