### ISSUE TITLE
Just had a Grott HA update, now not working

### ISSUE THREAD

**Issue by chesterflaps** [muppet3000/homeassistant-grott#32]
I have just updated Grott in HA and now when I start the Grott add on, it stops after a few minutes and I get no solar information.

Tried a reboot.

**Comment by muppet3000** [comment]
Sorry @chesterflaps  - You're posting this in the wrong repo, if you're using the HA Add-on which runs grott and you're having problems with that you need to post over in the @egguy repo here: https://github.com/egguy/grott-home-assistant-add-on

This repo is just for the integration which visualises the data.

Note - I have seen your other posted issues, I just haven't had the time to read and respond to them yet.

**Comment by chesterflaps** [comment]
I removed mqttinverterintopic="True" from grott.ini and then added it back in and BOOM it started working

how very odd
