### ISSUE TITLE
[Question] Why use homeassistant-grott

### ISSUE THREAD

**Issue by AdeZwart** [muppet3000/homeassistant-grott#37]
Hi, 

Like the title already implies, I'm missing a section on the readme file on why I should use this (HACS) integration. More explicitely: What benefit does this bring, over just having grott send all I need over MQTT to my HA instance?

Thanks!

**Comment by muppet3000** [comment]
Hi @AdeZwart  that's a really good question and something I should try to cover in the readme.

In the meantime I'll answer it here with some bullet points:
1. This integration works by consuming the data from MQTT, so you'd still need to have grott send the data to MQTT
2. This integration understands the format of all the data that Grott pushes to MQTT and performs the mappings onto supported types in Home Assistant e.g. VOLTAGE, WATTAGE etc
3. This integration also performs additional calculations to produce the values that are available in the growatt server webpage and not natively available in Grott MQTT values
4. I'm going to add functionality in the future to allow configuration to be pushed as well (which is pretty cool).

I hope that helps to answer the question, if you think of anything else please let me know.

**Comment by J4CE2** [comment]
Hi @muppet3000 do you know if this will also work with "shinewifi-x" dongle?
It looks slightly different to the shinelink one.
FYI - https://www.austraenergy.com.au/wp-content/uploads/2020/05/Growatt-Wi-Fi-Guidance.pdf

**Comment by muppet3000** [comment]
@J4CE2  - Yes - Take a look here: https://github.com/muppet3000/homeassistant-grott/issues/26 (I need to update the documentation)

**Comment by J4CE2** [comment]
Thanks mate, I did actually find that after I posted too (I should have looked before posting).  Looks like I'll need to reset the dongle so I can access the web url to update the server address.

**Comment by AdeZwart** [comment]
Thanks @muppet3000. Very clear explanation, and it would indeed be helpful to have that available on the readme/documentation.
