### ISSUE TITLE
Growatt 6000TL3-S inverter serial is not recognized

### ISSUE THREAD

**Issue by altserg** [muppet3000/homeassistant-grott#46]
I have Growatt 6000TL3-S 3 phase inverter with serial JNE4A140B5. I receive following error in the logs: - Inverter serial not recognised - using inverter type default.

However, some data are parsed and displayed via MQTT:

{"device": "JNE4A140B5", "time": "2023-10-03T16:49:10", "buffered": "no", "values": {"datalogserial": "DELETED", "pvserial": "JNE4A140B5", "pvstatus": 1, "pvpowerin": 6040, "pv1voltage": 3401, "pv1current": 9, "pv1watt": 3060, "pv2voltage": 2980, "pv2current": 10, "pv2watt": 2980, "pvpowerout": 5630, "pvfrequentie": 4993, "pvgridvoltage": 4062, "pvgridcurrent": 10, "pvgridpower": 2340, "pvgridvoltage2": 4093, "pvgridcurrent2": 9, "pvgridpower2": 2122, "pvgridvoltage3": 4062, "pvgridcurrent3": 10, "pvgridpower3": 2340, "pvenergytoday": 62, "pvenergytotal": 183548, "totworktime": 93620845, "pvtemperature": 336, "pvipmtemperature": 368, "epv1today": 37, "epv1total": 109628, "epv2today": 34, "epv2total": 96168, "epvtotal": 205796}}

**Comment by muppet3000** [comment]
Cool. so what's the issue?

**Comment by altserg** [comment]
I receive the message: "Inverter serial not recognised - using inverter type default" - is this normal ?  When I look at the source code, there is a separate message decode table for TL3 invertors, and if using the default type, it's most probably not used

**Comment by muppet3000** [comment]
You can specify one of those values to get additional values if it maps on to your specific type e.g. I have an SPH inverter, I set my config value to "sph" and I get all the battery info shown as well.
I don't think it's an error to be worried about, but you could set it to TLX and see if you get any more values.

**Comment by altserg** [comment]
I have realized that I have submitted this issue into wrong repository, closing

**Comment by muppet3000** [comment]
Could you let me know what the resolution is please @altserg  or link the other ticket if you raise one? I'd like to be able to help people out in the future

**Comment by altserg** [comment]
Moved to https://github.com/johanmeijer/grott/issues/432
