### ISSUE TITLE
homeassistant-grott sensors are not displayed in HASS energy dashboard setup

### ISSUE THREAD

**Issue by altserg** [muppet3000/homeassistant-grott#47]
I have installed Grott and Homeassistant-grott, and managed to get the inverter data to HASS via MQTT. I can see sensors like 
sensor.jne4a140b5_pv_all_energy_total, sensor.jne4a140b5_pv1_energy_today, etc. I also see that those sensors are updated on regular basis every 5 min.

However, those sensors are not showing up in the configuration of the energy dashboard, so I cannot configure solar production. 

![image](https://github.com/muppet3000/homeassistant-grott/assets/79573763/5ced27d7-b8d2-4f05-80b5-76506b57a8ae)
![image](https://github.com/muppet3000/homeassistant-grott/assets/79573763/8bbfd586-7197-4075-a079-d06471e14eb4)

**Comment by altserg** [comment]
![image](https://github.com/muppet3000/homeassistant-grott/assets/79573763/2c5ff4c3-2547-40ee-8282-fb8c0c891384)

I also have a question - what is the difference between "PV All-energy Total" and "Power Generation - Total (pvenergytotal)" sensors ? Stangely enough, they show different numbers in my case, and Growatt app shows the number equal to "Power Generation - Total (pvenergytotal)"

**Comment by muppet3000** [comment]
I can't explain why that value isn't being explained. I have exactly the same sort of setup myself and I have those values being plumbed through.
How long have you had the system up and running for with data coming in from Grott?

**Comment by altserg** [comment]
I have figured out the problem. Recorder statistics were disabled for all growatt entities. When I maually enabled the total energy output, it was shown in the energy dashboard. Maybe it makes sense to add this to documenation,
Closing the issue

**Comment by muppet3000** [comment]
> I have figured out the problem. Recorder statistics were disabled for all growatt entities. When I maually enabled the total energy output, it was shown in the energy dashboard. Maybe it makes sense to add this to documenation, Closing the issue

Please can you show me what you did to fix this?

**Comment by altserg** [comment]
Edited the recorder section of HASS configuration.yaml file. Manually added the "JNE4A140B5 Power Generation - Total (pvenergytotal)" sensor to record statistics. This is problem with user local config, not the addon

**Comment by muppet3000** [comment]
Oh I see, mine just does all that by default. Have you got 'recorder' disabled globally and you have to opt-in for each stat that you want?
