### ISSUE TITLE
Cannot connect to ShineWiFi-X

### ISSUE THREAD

**Issue by shocker2** [muppet3000/homeassistant-grott#5]
Hello,  
  Not sure if the procedure for WiFi is different from the LAN version (seen in the example that the LAN model is mentioned), but with default ports 80 and 443 I cannot access the data logger. Is there another way to access the web interface?

My invertor: MID 20KTL3-X1 (set in grott.ini config as tl3).
Datalogger: ShineWiFi-X, firmware: 3.1.0.5

Thanks

**Comment by muppet3000** [comment]
@shocker2 - Thanks for the self-solve. If you're able/willing to share some screen grabs I'll update the documentation to reflect this.

**Comment by muppet3000** [comment]
Is it this?
![image](https://github.com/muppet3000/homeassistant-grott/assets/10612068/5bc50101-f33a-4815-af6c-4f65b911366e)

If it is then I'm totally changing all the documentation for that?

Although, you can't change the update interval from there which is a shame. I'm sure I've got some details somewhere on how to change the update interval for other types of systems.

**Comment by shocker2** [comment]
Yes, it's that one.


<img width="831" alt="image" src="https://github.com/muppet3000/homeassistant-grott/assets/24977727/1ea01401-896b-465a-9ccf-1efa9dd69089">

**Comment by muppet3000** [comment]
Found it....
What about this: https://community.home-assistant.io/t/growatt-server-integration-interval/207840/9?u=muppet3000

That's the way I've seen people be able to change the update interval.

**Comment by shocker2** [comment]
Also, I can see that for TL3 there are only two phases shown in home assistant. I have added in the growatt.ini includeall = True, I'm waiting for the update.

**Comment by shocker2** [comment]
Only two phases unfortunatly 
<img width="223" alt="image" src="https://github.com/muppet3000/homeassistant-grott/assets/24977727/54ee37f9-1074-4129-ba97-8fd6bf23338e">

**Comment by shocker2** [comment]
Checked the log now and all phases are present, but in homeassistant I only have pv1 and pv2. Deleted the grott and re-added, same values. @muppet3000 any idea?

`grott        |   - date-time:  2023-05-12T16:34:26
grott        |   - Grott values retrieved:
grott        |           -  recortype1           :  0
grott        |           -  recortype2           :  124
grott        |           -  pvstatus             :  1
grott        |           -  pvpowerin            :  5154.1
grott        |           -  pv1voltage           :  498.4
grott        |           -  pv1current           :  3.0
grott        |           -  pv1watt              :  1495.2
grott        |           -  pv2voltage           :  414.2
grott        |           -  pv2current           :  2.6
grott        |           -  pv2watt              :  1076.9
grott        |           -  pv3voltage           :  667.7
grott        |           -  pv3current           :  3.7
grott        |           -  pv3watt              :  2470.4
grott        |           -  pvpowerout           :  5076.8
grott        |           -  pvfrequentie         :  50.0
grott        |           -  pvgridvoltage        :  231.8
grott        |           -  pvgridcurrent        :  7.4
grott        |           -  pvgridpower          :  1715.3
grott        |           -  pvgridvoltage2       :  237.5
grott        |           -  pvgridcurrent2       :  7.8
grott        |           -  pvgridpower2         :  1852.5
grott        |           -  pvgridvoltage3       :  235.0
grott        |           -  pvgridcurrent3       :  7.3
grott        |           -  pvgridpower3         :  1715.5
grott        |           -  Vac_RS               :  406.8
grott        |           -  Vac_ST               :  407.6
grott        |           -  Vac_TR               :  405.0
grott        |           -  pvenergytoday        :  39.5
grott        |           -  pvenergytotal        :  4681.0
grott        |           -  totworktime          :  1832.8
grott        |           -  epv1today            :  12.4
grott        |           -  epv1total            :  1313.1
grott        |           -  epv2today            :  7.8
grott        |           -  epv2total            :  1215.7
grott        |           -  epvtotal             :  4405.1
grott        |           -  pvtemperature        :  70.1
grott        |           -  pvipmtemperature     :  75.7
grott        |           -  pvboottemperature    :  65.0
grott        |           -  temp4                :  0.0
grott        |           -  uwBatVolt_DSP        :  0.0
grott        |           -  pbusvolt             :  3466
grott        |           -  nbusvolt             :  3463`

**Comment by muppet3000** [comment]
ok, create a new ticket for that one. I bet it's just that for my system that I based it on I didn't have those values.
In the new ticket can you highlight the specific values that are missing and what grott publishes them as?
I bet they're available in MQTT I just need to pull them out in the Integration.

**Comment by shocker2** [comment]
> ok, create a new ticket for that one. I bet it's just that for my system that I based it on I didn't have those values. In the new ticket can you highlight the specific values that are missing and what grott publishes them as? I bet they're available in MQTT I just need to pull them out in the Integration.

done

**Comment by shocker2** [comment]
also to get all values for tl3 I have added in the config the following:

```[Generic]
invtype=tl3
includeall = True
```

**Comment by muppet3000** [comment]
> > Found it.... What about this: https://community.home-assistant.io/t/growatt-server-integration-interval/207840/9?u=muppet3000
> > That's the way I've seen people be able to change the update interval.
> 
> interesting, I'll check when I'm back home and let you know

Did you ever get around to testing this? I'm hoping to update the documentation for people with the Wifi Sticks to have this info.

**Comment by shocker2** [comment]
> > > Found it.... What about this: https://community.home-assistant.io/t/growatt-server-integration-interval/207840/9?u=muppet3000
> > > That's the way I've seen people be able to change the update interval.
> > 
> > 
> > interesting, I'll check when I'm back home and let you know
> 
> Did you ever get around to testing this? I'm hoping to update the documentation for people with the Wifi Sticks to have this info.

Not yet as I'm not at home and for this I need to physically be near the device :). I'll try it out in the next couple of days and I'll let you know.

**Comment by muppet3000** [comment]
> > > > Found it.... What about this: https://community.home-assistant.io/t/growatt-server-integration-interval/207840/9?u=muppet3000
> > > > That's the way I've seen people be able to change the update interval.
> > > 
> > > 
> > > interesting, I'll check when I'm back home and let you know
> > 
> > 
> > Did you ever get around to testing this? I'm hoping to update the documentation for people with the Wifi Sticks to have this info.
> 
> Not yet as I'm not at home and for this I need to physically be near the device :). I'll try it out in the next couple of days and I'll let you know.

No problem at all, just wanted to check I hadn't missed an update that was all. No hurry. Thanks for the help.

**Comment by J4CE2** [comment]
> Yes, it's that one.
> 
> <img alt="image" width="831" src="https://user-images.githubusercontent.com/24977727/237982699-1ea01401-896b-465a-9ccf-1efa9dd69089.png">

I attempted this today. 
IP Address all updated successfully.
I have Grott server running on the IP I set.
Data is coming through still to Growatt Website.
But I cannot see any MQTT messages being published. 

Not sure what I am missing

**Comment by muppet3000** [comment]
Have you remembered to enable MQTT mode in Grott?
This is my config:
![image](https://github.com/muppet3000/homeassistant-grott/assets/10612068/dfb45ec5-b01f-47ea-8216-61ee67b5373b)
(The 'ip' is the hostname of the container that I'm running MQTT in)

**Comment by J4CE2** [comment]
> Have you remembered to enable MQTT mode in Grott? This is my config: ![image](https://user-images.githubusercontent.com/10612068/271499800-dfb45ec5-b01f-47ea-8216-61ee67b5373b.png) (The 'ip' is the hostname of the container that I'm running MQTT in)

Yeah,  I have that setup. 

`_MQTT:
        nomqtt                   False
        mqttip:                  192.168.1.xx
        mqttport:                1883
        mqtttopic:               energy/growatt
        mqttmtopic:              False
        mqttmtopicname:          energy/meter
        mqttinverterintopic:     False
        mqtttretain:             False
        mqtttauth:               False
        mqttuser:                mqtt_user
        mqttpsw:                 **secret**
`

I just shutdown the Grott server, and data is still coming into the Growatt website - I guess me updating the IP address has not taken effect (I did restart the dongle). 

Device Type：ShineWiFi-X 
Firmware Version：3.1.0.2

**Comment by muppet3000** [comment]
> > Have you remembered to enable MQTT mode in Grott? This is my config: ![image](https://user-images.githubusercontent.com/10612068/271499800-dfb45ec5-b01f-47ea-8216-61ee67b5373b.png) (The 'ip' is the hostname of the container that I'm running MQTT in)
> 
> Yeah, I have that setup.
> 
> > _MQTT:
> > nomqtt                   False
> > mqttip:                  192.168.1.xx
> > mqttport:                1883
> > mqtttopic:               energy/growatt
> > mqttmtopic:              False
> > mqttmtopicname:          energy/meter
> > mqttinverterintopic:     False
> > mqtttretain:             False
> > mqtttauth:               False
> > mqttuser:                mqtt_user
> > mqttpsw:                 **secret**
> 
> I just shutdown the Grott server, and data is still coming into the Growatt website - I guess me updating the IP address has not taken effect (I did restart the dongle).
> 
> Device Type：ShineWiFi-X Firmware Version：3.1.0.2

Yeah if the change hasn't been pushed to the dongle/wifi stick then grott won't be receiving anything.
Grott has pretty verbose logging so you should be able to see the output when there's content going in.

**Comment by J4CE2** [comment]
> Yeah if the change hasn't been pushed to the dongle/wifi stick then grott won't be receiving anything.
> Grott has pretty verbose logging so you should be able to see the output when there's content going in.

Thanks - yeah I can see logs in Grott if I test it via a browser... but nothing else at all. 
Ah well, may need to reset my dongle into AP Mode and apply the IP address change there.

**Comment by muppet3000** [comment]
> > Yeah if the change hasn't been pushed to the dongle/wifi stick then grott won't be receiving anything.
> > Grott has pretty verbose logging so you should be able to see the output when there's content going in.
> 
> Thanks - yeah I can see logs in Grott if I test it via a browser... but nothing else at all. Ah well, may need to reset my dongle into AP Mode and apply the IP address change there.

I'm not sure what you're testing via a browser, can you explain?
You need to use the IP of the machine running grott in the configuration of the wifi stick (apologies if this sounds patronising, just trying to be clear).

**Comment by J4CE2** [comment]
> > > Yeah if the change hasn't been pushed to the dongle/wifi stick then grott won't be receiving anything.
> > > Grott has pretty verbose logging so you should be able to see the output when there's content going in.
> > 
> > 
> > Thanks - yeah I can see logs in Grott if I test it via a browser... but nothing else at all. Ah well, may need to reset my dongle into AP Mode and apply the IP address change there.
> 
> I'm not sure what you're testing via a browser, can you explain? You need to use the IP of the machine running grott in the configuration of the wifi stick (apologies if this sounds patronising, just trying to be clear).

When I say testing via browser, I am just hitting my grott server IP on port 5279 in the browser. This simply generates an incorrect message, but at least proves my Grott server is running ok and generates my first log message.

And yes of course, I have my Grott server IP specified in the wifi stick - I imagine the web interface is not setting it correctly and I probably just need to use AP mode - something I'll try another time.

**Comment by Aad3229** [comment]
Can I leave the "Set domain" unchanged? 
If I change the IP in the datalogger to my Grott server, if I ever want to revert this and not use Grott anymore, what IP do I put in the "Set IP" to have the data sent directly to Growatt again?  Or do I just leave this blank to have the data being sent to Growatt again?

**Comment by muppet3000** [comment]
You can set it back to server.growatt.com
There's a discussion on 'reverting to stock for a non-tech' over here if you're interested: https://github.com/muppet3000/homeassistant-grott/issues/4

**Comment by J4CE2** [comment]
I managed to eventually get it working using this suggestion: https://community.home-assistant.io/t/growatt-server-integration-interval/207840/9?u=j4ce

It took a few goes but eventually it seems to be working. 
Data is still going to Growatt servers, and I can see Grott is receiving and pushing MQTT msgs now. Yay.

**Comment by muppet3000** [comment]
That's good to hear @J4CE2 

Note - This still makes use of the Growatt servers so, when they go down your data feed will stop.
I'm currently experimenting with grottserver to see how it behaves with the Growatt Servers out of the loop.

**Comment by J4CE2** [comment]
Thanks for that. Only small issue I have now is that last update time appears to be 7 hours behind (time zone??)

**Comment by muppet3000** [comment]
Are you running grott or MQTT in docker?
Remember to set the "environment" to include a `TZ` value, (looking at my config I did it just for grott (not for MQTT):
![image](https://github.com/muppet3000/homeassistant-grott/assets/10612068/79a713d7-edd5-4a53-8d1a-8bfb998c3717)

**Comment by J4CE2** [comment]
> Are you running grott or MQTT in docker? Remember to set the "environment" to include a `TZ` value, (looking at my config I did it just for grott (not for MQTT): ![image](https://user-images.githubusercontent.com/10612068/271756526-79a713d7-edd5-4a53-8d1a-8bfb998c3717.png)

Not using docker for MQTT or grott. Both servers appear to have the correct timezone and times set.

**Comment by muppet3000** [comment]
@J4CE2  - Did you work out what the issue was in the end?
Have you looked in the logs from Grott at all?

**Comment by J4CE2** [comment]
> @J4CE2 - Did you work out what the issue was in the end? Have you looked in the logs from Grott at all?

@muppet3000 actually Grott appears to be applying an offset for date/time value for some reason. I raised an issue here 
https://github.com/johanmeijer/grott/issues/428
