### ISSUE TITLE
PV3 missing on tl3 configuration

### ISSUE THREAD

**Issue by shocker2** [muppet3000/homeassistant-grott#6]
Hello,
  The values I have for home assistant:
<img width="213" alt="image" src="https://github.com/muppet3000/homeassistant-grott/assets/24977727/2a5b37d5-2e74-4f28-9c26-8dbf63249b9f">

Values on Grott
<img width="573" alt="image" src="https://github.com/muppet3000/homeassistant-grott/assets/24977727/ed2311ca-2976-48ff-a049-c9e1c66d162b">

For example the PV3 is missing.

```grott        |   - MQTT jsonmsg: 
grott        |                   {"device": "hidden", "time": "2023-05-12T16:42:12", "buffered": "no",
grott        |                   "values": {"datalogserial": "hidden", "pvserial": "hidden",
grott        |                   "recortype1": 0, "recortype2": 124, "pvstatus": 1, "pvpowerin": 53067,
grott        |                   "pv1voltage": 5011, "pv1current": 31, "pv1watt": 15534, "pv2voltage": 4114,
grott        |                   "pv2current": 28, "pv2watt": 11519, "pv3voltage": 6846, "pv3current": 38,
grott        |                   "pv3watt": 26014, "pvpowerout": 53007, "pvfrequentie": 4998,
grott        |                   "pvgridvoltage": 2312, "pvgridcurrent": 77, "pvgridpower": 17802,
grott        |                   "pvgridvoltage2": 2371, "pvgridcurrent2": 81, "pvgridpower2": 19205,
grott        |                   "pvgridvoltage3": 2345, "pvgridcurrent3": 76, "pvgridpower3": 17822,
grott        |                   "Vac_RS": 4057, "Vac_ST": 4070, "Vac_TR": 4041, "pvenergytoday": 404,
grott        |                   "pvenergytotal": 46818, "totworktime": 13197357, "epv1today": 126,
grott        |                   "epv1total": 13133, "epv2today": 79, "epv2total": 12158, "epvtotal": 44057,
grott        |                   "pvtemperature": 718, "pvipmtemperature": 769, "pvboottemperature": 674,
grott        |                   "temp4": 0, "uwBatVolt_DSP": 0, "pbusvolt": 3533, "nbusvolt": 3503}}```

**Comment by muppet3000** [comment]
Thanks, I based it on my own system (SPH) so may not have had all the values available for mapping. 
So, to be clear, it's all the ones titled 'pv3' that are missing right?

If that's the case it won't be too hard for me to add them in.

If you're able to give me an explicit list of the specific ones you're missing I can add them in when I'm next working on it.

**Comment by shocker2** [comment]
> Thanks, I based it on my own system (SPH) so may not have had all the values available for mapping. So, to be clear, it's all the ones titled 'pv3' that are missing right?
> 
> If that's the case it won't be too hard for me to add them in.
> 
> If you're able to give me an explicit list of the specific ones you're missing I can add them in when I'm next working on it.

pvstatus (online/offline)
pvenergytotal (not sure if that’s mapped as PV-All Energy - Total).
PV3 Current
PV3 Energy - Today
PV3 Energy - Total
PV3 Power
PV3 Voltage
totworktime

Also, I can see the "epv1today" not sure if you are taking the values from here and not from PV3 as I can see the "epv3" is missing from the list, and this might be the case for the missing data. Also not sure what the "e" stands for as it's not export, maybe energy :)

**Comment by muppet3000** [comment]
Hahaha, don't try and make any guesses about why things are called certain names, it's absolute chaos!

The names you've provided are the ones you want them to show up as/what they used to be called in the old integration. Can I get the names that they appear as in grott as then I can map them on to the new naming scheme.

I'll try and take a look at implementing this over the weekend.

**Comment by shocker2** [comment]
> Hahaha, don't try and make any guesses about why things are called certain names, it's absolute chaos!
> 
> The names you've provided are the ones you want them to show up as/what they used to be called in the old integration. Can I get the names that they appear as in grott as then I can map them on to the new naming scheme.
> 
> I'll try and take a look at implementing this over the weekend.

Indeed, I was trying to see any documentation for the names, and seems that there is none (or at least I cannot find it).

values to be mapped:
In general:
```
pvstatus
pvenergytotal
totworktime
```
the 3rd phase
```
pv3voltage
pv3current
pv3watt
```
for those two not sure what needs to be mapped, I think the values are missing
```
PV3 Energy - Today
PV3 Energy - Total
```

**Comment by muppet3000** [comment]
- `pvstatus` is already mapped to `PV Status` which is in the "Diagnostics" section of the device screen
- `totworktime` is already mapped to `Time Since Commissioned` (also in the "Diagnostics" section)
- `pvenergytotal` - I don't think I have that one on my SPH system, is that something like "PV generated total" i.e. it doesn't reset daily it's an all time total?

`pv3voltage` - added as `PV3 Voltage`
`pv3current` - added as `PV3 Current`
`pv3watt` - added as `PV3 Power`
`epv3today` - added as `PV3 Energy - Today`
`epv3total` - added as `PV3 Energy - Total`

If I could get some feedback on what `pvenergytotal` should display and I'll add that one in too.

(Please can you test this out for me? It's on the 'main' branch if you're ok with using that on HACS).

**Comment by shocker2** [comment]
Sorry for the noob question, do I need to re-download to apply the patch? Or should I go via ssh and replace the modified files? If the latter, what's the path in home assistant RPI?

![image](https://github.com/muppet3000/homeassistant-grott/assets/24977727/cc8f35f2-c8ff-45e2-b88f-5170dc40d241)

**Comment by shocker2** [comment]
Values are now automatically added, I'll check with the total values to see if everything is correct.

![image](https://github.com/muppet3000/homeassistant-grott/assets/24977727/b52dca63-f82d-4386-b4b2-45e448b456ff)

**Comment by shocker2** [comment]
Everything is correct now. PV-All Power = PV1 Power + PV2 Power + PV3 Power, thank you!

I have checked the "pvenergytotal" and this represent the total number of energy produced since the installation.

In logs: pvenergytotal        :  4774.6 
In app is the 4.8MWh
![image](https://github.com/muppet3000/homeassistant-grott/assets/24977727/bca3f764-45fe-4fb0-98e3-20a23974d6da)

Now there is one small bug, I cannot see the:  epv3today and epv3total but that's missing from grott, I'll raise an issue with them and let you know to update the config, or you can already update the config in advance for those missing values :)

Thank you!

**Comment by muppet3000** [comment]
> and this represent the total number of energy produced since the installation.

Thanks for the update. 

I've already added epv3today and epv3total to the config so whenever they appear in grott they'll start appearing in the HA integration as well.

I'll add in pvenergytotal next time I'm at my desk.

**Comment by shampeon** [comment]
My MIN-XH-US inverter has a PV4 input as well.

**Comment by muppet3000** [comment]
Hi All, just circling back to this one, I'm adding the PV4 entries as suggested by @shampeon after that I think this can be closed.

The `pvenergytotal` field is being implemented as part of #8

**Comment by muppet3000** [comment]
This functionality is now available on the `main` branch for testing (you can select this in the re-download menu in HACS)

**Comment by muppet3000** [comment]
Has anyone been able to confirm this works?
I'm closing this so that it can be marked as included in the next release.

**Comment by shocker2** [comment]
Still waiting for the bug fix on https://github.com/johanmeijer/grott/issues/339 but for PV4 i cannot confirm as I only have 3 phases :)

**Comment by muppet3000** [comment]
@shampeon - Are you able to confirm this as you seem to have PV3 & PV4 on the output you showed above.

**Comment by shampeon** [comment]
PV4 values are there, but missing the Energy - Total and Energy - Today values, presumably because they're missing from upstream (i.e. johanmeijer/grott#339).
<img width="317" alt="Screen Shot 2023-06-20 at 2 02 58 PM" src="https://github.com/muppet3000/homeassistant-grott/assets/5759834/3824e20e-b54d-4106-bfd1-c56b5298b81b">

**Comment by muppet3000** [comment]
Yeah if they're not available in MQTT yet then they won't appear. From my perspective it's enough to consider this one closed from my end, they should automagically appear in HA once they're being pushed in Grott.

**Comment by LightMoon** [comment]
I didn't want to open a new issue so I decided to piggyback. I am not able to see PV3 data, the steps I followed were bit different. I reckon at the time this issue was opened the grott-home-assistant-add-on hadn't been available.

The steps I have done: 
1- installed [grott-home-assistant-add-on](https://github.com/egguy/grott-home-assistant-add-on) by @egguy and set it up   per @muppet3000 guideline - ignored the configuration step.
1.  https://github.com/muppet3000/homeassistant-grott/blob/main/docs/setup/grott.md#grott-add-on 
2. https://www.splitbrain.org/blog/2023-11/03-growatt_and_home_assistant

2 - Proceeded with the installation of [homeassistant-grott](https://github.com/muppet3000/homeassistant-grott) integration.

What I am missing here?

<img width="721" alt="Screenshot 2023-12-14 at 3 37 35 pm" src="https://github.com/muppet3000/homeassistant-grott/assets/1636991/031f6968-b53f-4706-aa3a-75c515e0a54e">
<img width="338" alt="Screenshot 2023-12-14 at 3 37 52 pm" src="https://github.com/muppet3000/homeassistant-grott/assets/1636991/0dc239c6-7d31-4f82-9972-b966ebc8e2ca">

**Comment by muppet3000** [comment]
> I didn't want to open a new issue so I decided to piggyback. I am not able to see PV3 data, the steps I followed were bit different. I reckon at the time this issue was opened the grott-home-assistant-add-on hadn't been available.
> 
> The steps I have done: 1- installed [grott-home-assistant-add-on](https://github.com/egguy/grott-home-assistant-add-on) by @egguy and set it up per @muppet3000 guideline - ignored the configuration step.
> 
> 1. https://github.com/muppet3000/homeassistant-grott/blob/main/docs/setup/grott.md#grott-add-on
> 2. https://www.splitbrain.org/blog/2023-11/03-growatt_and_home_assistant
> 
> 2 - Proceeded with the installation of [homeassistant-grott](https://github.com/muppet3000/homeassistant-grott) integration.
> 
> What I am missing here?
> 
> <img alt="Screenshot 2023-12-14 at 3 37 35 pm" width="721" src="https://private-user-images.githubusercontent.com/1636991/290401464-031f6968-b53f-4706-aa3a-75c515e0a54e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MzY3MDQsIm5iZiI6MTcwMjUzNjQwNCwicGF0aCI6Ii8xNjM2OTkxLzI5MDQwMTQ2NC0wMzFmNjk2OC1iNTNmLTQ3MDYtYWEzYS03NWM1MTVlMGE1NGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMDY0NjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2NlYWJkYTIyNzc1MTkzZGU5OTU0OWUyMDhjYzdmOWFkMjFjNzgwZTM5ZDgxOWViYjBkYTRmZTk4YTA2MGU0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ze2yiju0G6cCY-AmWRx5NG2eTx_yFiADHWT-B-WS8a0"> <img alt="Screenshot 2023-12-14 at 3 37 52 pm" width="338" src="https://private-user-images.githubusercontent.com/1636991/290401483-0dc239c6-7d31-4f82-9972-b966ebc8e2ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MzY3MDQsIm5iZiI6MTcwMjUzNjQwNCwicGF0aCI6Ii8xNjM2OTkxLzI5MDQwMTQ4My0wZGMyMzljNi03ZDMxLTRmODItOTk3Mi1iOTY2ZWJjOGUyY2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMDY0NjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI0ZTQ1N2U0Zjg5ZmFlNzk3NzNhYjY2MzM4MmRmNDYxNjY3ZjE2NGFkMGJlMjM0ZWI4MTZkOTYwMDA1NzRiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.w0b63OYUR3Rf-6s46KOvGWBRf0HHNVSiheH7EA0GFEA">

You're probably not missing anything, please can you post the logs from grott so I can see what your system is actually publishing to grott. This integration simply consumes what's on the MQTT messages, so if it's not being published then it can't be consumed.
With those logs I should be able to work it out for you.

**Comment by LightMoon** [comment]
@muppet3000 Thanks for assisting me in figuring this out. here are the logs I could get from [grott-home-assistant-add-on](https://github.com/egguy/grott-home-assistant-add-on) - https://pastebin.com/kGyUipSH - https://pastebin.com/viKSD2Ss

and Log from Home Assistance Core

<img width="1251" alt="Screenshot 2023-12-15 at 11 06 39 am" src="https://github.com/muppet3000/homeassistant-grott/assets/1636991/148d68a8-705c-4546-ba9d-857b6056e8e5">

**Comment by muppet3000** [comment]
@LightMoon  - Looking at the logs, this is the important bit, this is what Grott is getting from your inverter:
```         -  datalogserial        :  XGD6CM31UN
         -  pvserial             :  SPM2DBE044
         -  voltage_l1           :  244.5
         -  voltage_l2           :  0.0
         -  voltage_l3           :  0.0
         -  Current_l1           :  16.0
         -  Current_l2           :  0.0
         -  Current_l3           :  0.0
         -  act_power_l1         :  -3310.5
         -  act_power_l2         :  0.0
         -  act_power_l3         :  0.0
         -  app_power_l1         :  3684.2
         -  app_power_l2         :  0.0
         -  app_power_l3         :  0.0
         -  react_power_l1       :  1683.3
         -  react_power_l2       :  0.0
         -  react_power_l3       :  0.0
         -  powerfactor_l1       :  -0.9
         -  powerfactor_l2       :  0.0
         -  powerfactor_l3       :  0.0
         -  pos_rev_act_power    :  -3310.5
         -  pos_act_power        :  -3310.5
         -  rev_act_power        :  -3310.5
         -  app_power            :  3684.2
         -  react_power          :  1683.3
         -  powerfactor          :  -0.9
         -  frequency            :  50.0
         -  L1-2_voltage         :  0.0
         -  L2-3_voltage         :  0.0
         -  L3-1_voltage         :  0.0
         -  pos_act_energy       :  333.2
         -  rev_act_energy       :  1860.2
```

So what ones of those aren't showing for you on home assistant? Looking at the code for this integration they all seem to be mapped through.

I think there's some other logs that are missing, if you're running a metered system you get two lots of output like how I've pasted above, is there another lot of output which contains things like `ppv2` or `pv2watt`?

If you can get another log output that contains the other stuff that would help me to understand what hasn't been mapped.

Looking at your screen grab from above I'm certain there will be a log entry with something looking similar to above but with either `ppv2` or `pv2watt` in it.

**Comment by LightMoon** [comment]
You're spot one! I restarted the addon and tailed the logs with this command  `ha host logs --identifier addon_1ef934e0_grott-beta -f`, `ppv2` and `pv2watt` showed up in the logs! - https://pastebin.com/pCbGbyd2


<img width="740" alt="Screenshot 2023-12-16 at 9 21 20 am" src="https://github.com/muppet3000/homeassistant-grott/assets/1636991/530d4617-25ab-417d-a595-fa2f789d19b9">
<img width="750" alt="Screenshot 2023-12-16 at 9 21 33 am" src="https://github.com/muppet3000/homeassistant-grott/assets/1636991/32183eba-33f1-4a56-9bab-5a82f4d4a701">
<img width="1372" alt="Screenshot 2023-12-16 at 9 25 06 am" src="https://github.com/muppet3000/homeassistant-grott/assets/1636991/4f268fa1-3eb1-42f0-b943-ddd260a5f08a">
<img width="1386" alt="Screenshot 2023-12-16 at 9 25 36 am" src="https://github.com/muppet3000/homeassistant-grott/assets/1636991/2e386108-9bc1-4ce5-a671-84e6468728d1">

**Comment by muppet3000** [comment]
Looking at those logs you're missing anything in them for pv3:
```
 "values": {"datalogserial": "XGD6CM31UN", "pvserial": "SPM2DBE044",
Dec 15 21:00:20 homeassistant addon_1ef934e0_grott-beta[400]:                          "pvstatus": 1, "pvpowerin": 51774, "pv1voltage": 1430, "pv1current": 69,
Dec 15 21:00:20 homeassistant addon_1ef934e0_grott-beta[400]:                          "pv1watt": 9962, "pv2voltage": 4130, "pv2current": 86, "pv2watt": 35653,
Dec 15 21:00:20 homeassistant addon_1ef934e0_grott-beta[400]:                          "pvpowerout": 0, "pvfrequentie": 0, "pvgridvoltage": 2484, "pvgridcurrent":
Dec 15 21:00:20 homeassistant addon_1ef934e0_grott-beta[400]:                          0, "pvgridpower": 0, "pvgridvoltage2": 0, "pvgridcurrent2": 0,
Dec 15 21:00:20 homeassistant addon_1ef934e0_grott-beta[400]:                          "pvgridpower2": 2365980672, "pvgridvoltage3": 15672, "pvgridcurrent3": 72,
Dec 15 21:00:20 homeassistant addon_1ef934e0_grott-beta[400]:                          "pvgridpower3": 580583424, "Vac_RS": 45, "Vac_ST": 0, "Vac_TR": 27140,
Dec 15 21:00:20 homeassistant addon_1ef934e0_grott-beta[400]:                          "pvenergytoday": 30096, "pvenergytotal": 9, "totworktime": 3879,
Dec 15 21:00:20 homeassistant addon_1ef934e0_grott-beta[400]:                          "epv1today": 33, "epv1total": 12641, "epv2today": 0, "epv2total": 0,
Dec 15 21:00:20 homeassistant addon_1ef934e0_grott-beta[400]:                          "epvtotal": 0, "pvtemperature": 492, "pvipmtemperature": 492,
Dec 15 21:00:20 homeassistant addon_1ef934e0_grott-beta[400]:                          "pvboottemperature": 0, "uwBatVolt_DSP": 449, "pbusvolt": 4179, "nbusvolt":
Dec 15 21:00:20 homeassistant addon_1ef934e0_grott-beta[400]:                          0}}
```
I would recommend logging a bug in either of these two repos to get some assistance with why this isn't being picked up for your system:
https://github.com/egguy/grott-home-assistant-add-on
or
https://github.com/johanmeijer/grott/
