### ISSUE TITLE
clarification and more precise how to set it up for a mqtt newbie

### ISSUE THREAD

**Issue by typxxi** [muppet3000/homeassistant-grott#79]
I had started following this project over a year ago and later found the HA growatt integraton using the api which back then had been working. 
Since then I had been banned, trouble with growatt and they with me as a customer owning right now in total 18 growatt inverters, 8 or 9 active. 

That being a said I had digged into the HA Grott version last year in may or so and worked on the documentation and a schematic back then. Now I came back and had developed a full misunderstanding as I assume.

I had thought that running my HA OS on a pi-5 would require a 2nd machine to act as a grott server / middleman. 

And I had not understood or forgotten that this only temporarily needed til I can make sure that I have a working grott setup which I then could reuse once I have installed this HACS HA Grott addon.

My fault but I guess it would be great to make this very clear that not 2 machines are required later, only due to the setup and configuring time. 

I will have to start now or on the weekend from scratch and setup a raspberry pi 3 as Pi OS system running a native Grott server and starting to make that running at least with 1 or all my 8 growatt inverters 

Do I really need to setup all 8 or is 1 good enough to carry on inside HA OS and the HA Grott addon ?
I do not want to change 8 inverters IP or ShineWiFi Sticks IP just for testing.

I also had tried to find a good documentation how to set it up properly or a youtube video but I had not found much that was really explaining step by step what to do. Just bits and pieces here and there and also for all the different HA setups. 

I hope someone can answer my general question if I got it right now that the Grott server on a dedicated hardware is only temporarily and that I could start working with the HA Grott addon once I have one or 2 inverters running with the dedicated grott server.

thanks a lot !

**Comment by muppet3000** [comment]
Hi @typxxi  - It looks like you found the documentation in the end (looking at your comments on #80 are you happy to close this one?

**Comment by typxxi** [comment]
more than happy to close it now cause I will write my experience up and send it to you once it is done .

Setup will be HA on pi 4 or Pi 5 and grott on Pi 3 as dedicaded grott proxy server for about 8 growatt inverters reporting every minute to growatt the data - and to HA mqttt broker of cause. I guess this summer I will have put that together once my system is stable running and before I will start the ems and battery charging adventure where I guess that I will have to use modbus to get the data when to charge and for how long to the SPH hybrid inverter.
