### ISSUE TITLE
In case a Growatt inverter might be needed: our fleet consists out of MiN 4600, MiC 3000, MiC 2000, MiC 600 and SPH 4600

### ISSUE THREAD

**Issue by typxxi** [muppet3000/homeassistant-grott#80]
In the past 3 days I have finally successfully installed Grott standalone on a Pi3 running as a usual python program. 
ommunication to my Pi 4 Homeassistand and mqqt has been successfully established and when I wanted to install sensors manually I ran into problems and checked the HA grott documentation again to find out that I had already achieved everything required for HA grott.

When I tried to install I ran out of time cause the sun was already gone, but I have installed the grott ha integration so far, but my mqtt is now quiet till tomorrow morning. 

We have a few growatt inverters, sometime multiple so in case a check might be needed I can do that hopefully quite soon. 
We have EU version incl. 10 year warranty so the usual devices and no direct import from china.

My current setup is using a pi4 as HA server and a pi 3 for the grott applicaiton which might move to a Pi Zero W over time or to the new HA server, which will be a Pi-5 4GB but when I am able and familiar how to setup grott as container under Hassio or however that might be possible. 

I also want to thank you for the project developement and for the good documentation which is a lot better than the grott documentation which had caused a lot of headache and pain in the past 3 or 4 days till I finally saw the values arriving in mqqt this early morning. The biggest flaw was the basic grott.ini from the examples directory which mentioned all the mqtt settings. Even though the user id and pw were set there i had not thought that I would have to enable auth = true which is set by default as False and that was the reason why I did not receive the message for over a day or 2 .

THANKS

**Comment by muppet3000** [comment]
Hi @typxxi - Thanks for the feedback, if there's anything I can do to improve my documentation please let me know here and I'll make changes.
I'm really hoping that over time I can make this the 'go-to' source of instructions for configuring Grott.

Given you have such a wide range of inverters - how does Grott handle that? Do you have 1 grott instance for each of your inverters or does it auto-detect type for each one of them? I thought you had to tell it what type the inverter was in the grott.ini and therefore the MiN and SPH would be different values?

**Comment by typxxi** [comment]
to close this one my reply which I had given before today:

* I will write a summary of how to set a growatt inverter up with grott on a pi to deliver the data back to growatt servers and to home assistant for 1 or multiple inverters. but as you know it will take time but you will get an answer or input from me
* regarding the grott instance question I guess you mean that if I have one raspberry pi for all my inverters or 2 ?
No, I have just one.
but if you meant that if I had 2 grott instances of your grott integration if you can call it that way I have to clarify things first.

Did you mean this point?
![image](https://github.com/muppet3000/homeassistant-grott/assets/20662430/b6e0862e-1748-440d-a525-cc7181e43693)

If so I can tell you that i had mistakenly pressed the button below "add entry" or Eintrag hinzufügen at this spot
![image](https://github.com/muppet3000/homeassistant-grott/assets/20662430/14c68cbb-88b2-4145-867f-31d6589adaf2)

Afterwards a second element also called grott appeared which you could mean with 2nd grott instance .

I have to admit that I found it weird and I nothing read about that so i wanted to get rid off that 2nd grott imediately. 
That being said I had changed the destination IP from my other inverters one after the other over 3 days in batches of 2 or 3 by simply editing the wifi stick settings via web and growatt server pave. Once I pressed save there on the growatt wifi stick setup the traffic was rerouted from the growatt server to my pi 3 grott "proxy" which then forwarded the messages to the growatt server (which I had checked over days and all routers if the data and the same would still arrive) AND to the mqtt server / broker on my HA installation .

And for whatever reason my 1 and only HA grott instances has been populated which means that first the device appeared there, so I had 3 devices instead of 2 with 68 entities. Within minutes (my wifi stick have a 1 minute reporting not the default 5 minute reporting) my grott instance was populate with the 4th inverter and then also with some sensors appearing , I mean I had more than 68 entities but not 102 . At least it felt for me so that while the mqtt messages arrived they were handled and caused your grott integration to create the new sensors. 

Sorry, but I did not observe the whole process or intervened, I simply waited and gave the system time to do the work while I checked on the pi3 if further inverters were sending messages or not cause I had made a list to write down which inverter id with which logger id when appeared for the first time on the pi-3 and if that caused error messages or not cause I had spent the days before with mistake by mistake during the grott installation or maybe not clear enough instruction and the most important one the grott.ini mqtt setting auth = False with the following lines for the mqtt ha userid and its password, cause this has to be set to auth = True . It had cost me hours cause I simply did not believe that a change was neccessary if the author mention user and password . I saw the authentification failed message, changed password and what not till I finally thought twice if I really would have to change that to true or not.  

After all that mess on the grott setup side on my pi3 which I had thought to be easy, I was very carefull with the installation of the grott ha integration cause I expected a lot more pitfalls than during my grott installation, therefore I was very reluctant to push the grott ha system and did not update, but checked the grott pi3 server side . However the inverters appeared one after the other as all the 34 sensors appeared for all 7 inverters. Also the renaming of each inverter and its entities worked like a charm. I am quite happy so far regarding how it is performing for the past 3 days at least cause I started the setup saturday evening and suddenly on sunday morning not only the messages were reappearing in the mqtt explorer but also the grott instance become alive again which means the messages once you open a device / inverter
Here in the right column I can check if the messaging and reporting into HA is still alive
![image](https://github.com/muppet3000/homeassistant-grott/assets/20662430/b07a6423-a769-45e9-8a24-19958b252630)
 
From the fleet of inverters mentioned above all are working fine somehow (I call it this way cause I have done nothing like editing a list of inverters and id, wifi stick and what not - only for me on paper and note++ to make sure it is working properly) except 1 inverter.
The SPH 4600 has not my final OK cause the battery is not ready and therefore I have not checked that inverter at all in general and of cause not in HA, but in case of trouble or bugs I will write about. But the 1 phase SPH series sph 3000 to 6000 is a quite old and reliable one with its own flaws, quirks and features, not so famous for being totally buggy in the integration. 

I will close this comment cause you are aware in case you need some testing it in a multi inverter setup or for one of these inverters cause I tend to have also another one, the most important "brother", the spare. So I can play around with such cause I also have 10 or 12 not connected panels from used 240 Wp up to most recenty 600 Wp high current panels.    
Therefore I do not have to risk much in such cases cause it will be an isolated testbed in case you need such support. 

Great job, quite happy and I will contribute and support the developement too.

**Comment by typxxi** [comment]
Was never an issue, just an offer as it is in the future therefore closed.
