### ISSUE TITLE
Docker compose with GrottServer

### ISSUE THREAD

**Issue by BerthaG63** [muppet3000/homeassistant-grott#87]
Hi Muppet,

Great work, this is very well written and documented.

I saw you had a docker-composed for Grott will it be this one for the server version :

  #GrottServer
  grottserver:
    container_name: grott
    image: ledidobe/grottserver:2.8.3
    volumes:
      - ./grott/output:/tmp/grottlog/
      - ./grott/config/grott.ini:/app/grott.ini
    ports:
      - 5279:5279
    restart: unless-stopped

Any thing particular or we can act like it is Grott but locally ?

Thanks again for your great repo.

Regards

**Comment by typxxi** [comment]
this is not a real issue of the integration cause this integration is based on a running grott installation.
Your question belongs to the grott server itself if you really wanna get help - 3 months later now and I expect no one will help you here off topic cause the likelihood that others can find and benefit from that is low. 

Here your no issue entry is making the list of open issues unnecessary longer which is not a good impression for new users.
Might be time to close this issue which never was an issue of the integration.
