### ISSUE TITLE
Energy sensor

### ISSUE THREAD

**Issue by InvertedMinor** [muppet3000/homeassistant-grott#90]
There is no energy sensor showing up for the energy dashboard. Is there a workaround?

**Comment by typxxi** [comment]
What do you expect if the description is so short ? 
Have you configure the integration properly you will get something like this 
![image](https://github.com/user-attachments/assets/0e444daf-7a24-47c1-89f3-8bd927e35e86)

Those are 8 inverters with more than 400 sensors - and you simply have to set up your energy dashboard properly to get it right. No issue of this integration afaik and therefore please close it cause your non issue is making the list of real issues unnecessary longer which is not the best impression for new users.

**Comment by InvertedMinor** [comment]
thnx found it.
